baseURL: "https://osuoverclocking.com"
languageCode: "en-us"
theme: ["gohugo-theme-ananke"]

DefaultContentLanguage: "en"

pagination:
  pagerSize: 24
googleAnalytics: ""
enableRobotsTXT: true

module:
  mounts:
    - source: content/en
      target: content

menus:
  main:
  - name: Posts
    pageref: /posts
    weight: 10
  - name: Leadership
    pageref: /leadership
    weight: 20

languages:
  en:
    title: Overclocking Club
    weight: 1

sitemap:
  changefreq: monthly
  priority: 0.
  filename: sitemap.xml

params:
  text_color: "bg-near-white med-width"
  favicon: "/img/favicon.png"
  description: "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-osu"
  recent_posts_number: 4
  custom_css: ["style.css"]
  body_classes: "avenir bg-near-white"
  ananke:
    social:
      follow:
        networks: [ "hwbot", "github", "discord" ]
      networks:
      - name: discord
        slug: "discord"
        label: "Discord"
        color: "#7289da"
        profile: "false"
        icon: "discord" # font awesome brand icon name
      - name: hwbot
        slug: "hwbot"
        label: "HWBot"
        color: "#7289da"
        profile: "https://hwbot.org/user/%s"
        icon: "hwbot" # font awesome brand icon name
      - name: github
        slug: "github"
        label: "GitHub"
        color: "#6cc644"
        profile: "https://github.com/%s/"
        icon: "github" # font awesome brand icon name
      github:
        username: "osu-overclocking"
      discord:
        profileLink: "https://discord.gg/m46VKy2ZDE"
      hwbot:
        username: "benny_benches"

markup:
  goldmark:
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
        title: true
