baseURL: "https://osuoverclocking.com"
languageCode: "en-us"
theme: ["gohugo-theme-ananke"]
resourceDir: "resources"
contentDir: "content/en"

DefaultContentLanguage: "en"
SectionPagesMenu: "main"
Paginate: 24
googleAnalytics: ""
enableRobotsTXT: true

languages:
  en:
    title: OSU Overclocking Club
    weight: 1
    contentDir: content/en

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

params:
  text_color: "bg-near-white med-width"
  author: ""
  favicon: "/img/favicon.png"
  site_logo: ""
  description: "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-osu"
  recent_posts_number: 4
  custom_css: ["style.css"]
  body_classes: "avenir bg-near-white"
  ananke_socials:
  - name: github
    url: https://github.com/osu-overclocking
  - name: HWBot
    url: https://hwbot.org/user/benny_benches/
  - name: discord
    url: https://discord.gg/m46VKy2ZDE
  - name: matrix
    url: https://matrix.to/#/!oqVetIcDFOwVNLcRDZ:matrix.org

markup:
  goldmark:
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
        title: true

  
